version: "3.8"
name: "script_writer_electric"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: script_writer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    command:
      - -c
      - wal_level=logical
      - -c
      - listen_addresses=*
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/server/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d script_writer"]
      interval: 5s
      timeout: 5s
      retries: 5

  electric:
    image: electricsql/electric:1.0.19
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/script_writer?sslmode=disable
      # Not suitable for production. Only use insecure mode in development or if you've otherwise secured the Electric API.
      # See https://electric-sql.com/docs/guides/security
      ELECTRIC_INSECURE: true
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
