/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import { TypedJsondoc } from "@/common/types";
import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Jsondocs {
  created_at: Generated<Timestamp>;
  data: string;
  id: string;
  metadata: string | null;
  origin_type: string;
  project_id: string;
  schema_type: TypedJsondoc['schema_type'];
  schema_version: TypedJsondoc['schema_version'];
  streaming_status: Generated<string | null>;
  updated_at: Generated<Timestamp>;
}

export interface JsondocYjsAwareness {
  jsondoc_id: string;
  client_id: string;
  created_at: Generated<Timestamp | null>;
  project_id: Generated<string>;
  room_id: string;
  update: Buffer;
  updated_at: Generated<Timestamp | null>;
}

export interface JsondocYjsDocuments {
  jsondoc_id: string;
  created_at: Generated<Timestamp | null>;
  document_state: Buffer;
  id: Generated<number>;
  project_id: Generated<string>;
  room_id: string;
  updated_at: Generated<Timestamp | null>;
}

export interface AuthProviders {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  provider: string;
  provider_data: string | null;
  provider_id: string;
  user_id: string;
}

// New conversation tables
export interface Conversations {
  id: Generated<string>;
  project_id: string;
  type: string; // 'agent' | 'tool'
  status: Generated<string>; // 'active' | 'completed' | 'failed'
  metadata: Generated<Json>;
  created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface ConversationMessages {
  id: Generated<string>;
  conversation_id: string;
  role: string; // 'system' | 'user' | 'assistant' | 'tool'
  content: string;

  // Tool-specific fields
  tool_name: string | null;
  tool_call_id: string | null;
  tool_parameters: Json | null;
  tool_result: Json | null;

  // LLM parameters
  model_name: string | null;
  temperature: Numeric | null;
  top_p: Numeric | null;
  max_tokens: number | null;
  seed: number | null;

  // Caching support
  content_hash: string | null;
  cache_hit: Generated<boolean>;
  cached_tokens: Generated<number>;

  // Status tracking
  status: Generated<string>; // 'streaming' | 'completed' | 'failed'
  error_message: string | null;

  // Metadata
  metadata: Generated<Json>;
  created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface ConversationMessagesDisplay {
  id: Generated<string>;
  conversation_id: string;
  raw_message_id: string;
  role: string; // 'user' | 'assistant'
  content: string;
  display_type: Generated<string>; // 'message' | 'thinking' | 'progress'
  created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface ProjectCurrentConversations {
  project_id: string;
  conversation_id: string;
  updated_at: Generated<Timestamp>;
}

export interface HumanTransforms {
  action_type: string;
  change_description: string | null;
  derivation_path: Generated<string | null>;
  derived_jsondoc_id: string | null;
  interface_context: string | null;
  project_id: string;
  source_jsondoc_id: string | null;
  transform_id: string;
  transform_name: string | null;
}

export interface LlmPrompts {
  id: string;
  project_id: string;
  prompt_role: Generated<string | null>;
  prompt_text: string;
  transform_id: string;
}

export interface LlmTransforms {
  model_name: string;
  model_parameters: string | null;
  project_id: string;
  raw_response: string | null;
  token_usage: string | null;
  transform_id: string;
}

export interface Projects {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: string;
  project_title_manual_override: Generated<boolean>;
  project_type: Generated<string | null>;
  status: Generated<string | null>;
  title: string;
}

export interface ProjectsUsers {
  id: Generated<number>;
  joined_at: Generated<Timestamp>;
  project_id: string;
  role: Generated<string | null>;
  user_id: string;
}

export interface TransformInputs {
  jsondoc_id: string;
  jsondoc_path: Generated<string>;
  id: Generated<number>;
  input_role: string | null;
  project_id: string;
  transform_id: string;
}

export interface TransformOutputs {
  jsondoc_id: string;
  id: Generated<number>;
  output_role: string | null;
  project_id: string;
  transform_id: string;
}

export interface Transforms {
  created_at: Generated<Timestamp>;
  error_message: string | null;
  execution_context: string | null;
  id: string;
  max_retries: Generated<number | null>;
  progress_percentage: Numeric | null;
  project_id: string;
  retry_count: Generated<number | null>;
  status: Generated<string | null>;
  streaming_status: string | null;
  tool_call_id: string | null;
  type: string;
  type_version: Generated<string>;
  updated_at: Generated<Timestamp>;
  // New conversation tracking columns
  conversation_id: string | null;
  trigger_message_id: string | null;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string | null;
  id: string;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface EmbeddingCache {
  content_hash: string;
  content_text: string;
  embedding: string; // pgvector type represented as string
  model_name: string;
  provider: string;
  dimensions: Generated<number>;
  created_at: Generated<Timestamp>;
  accessed_at: Generated<Timestamp>;
  access_count: Generated<number>;
}

export interface Particles {
  id: string;
  jsondoc_id: string;
  project_id: string;
  path: string;
  type: string;
  title: string;
  content: Json;
  content_text: string;
  embedding: string | null; // pgvector type represented as string
  content_hash: string | null; // New field
  is_active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface UserSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  user_id: string;
}

export interface DB {
  jsondoc_yjs_awareness: JsondocYjsAwareness;
  jsondoc_yjs_documents: JsondocYjsDocuments;
  jsondocs: Jsondocs;
  auth_providers: AuthProviders;
  conversations: Conversations;
  conversation_messages: ConversationMessages;
  conversation_messages_display: ConversationMessagesDisplay;
  project_current_conversations: ProjectCurrentConversations;
  embedding_cache: EmbeddingCache;
  human_transforms: HumanTransforms;
  llm_prompts: LlmPrompts;
  llm_transforms: LlmTransforms;
  particles: Particles;
  projects: Projects;
  projects_users: ProjectsUsers;
  transform_inputs: TransformInputs;
  transform_outputs: TransformOutputs;
  transforms: Transforms;
  user_sessions: UserSessions;
  users: Users;
}
