/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Artifacts {
  created_at: Generated<Timestamp | null>;
  data: string;
  id: string;
  metadata: string | null;
  partial_data: Json | null;
  project_id: string;
  streaming_progress: Generated<Numeric | null>;
  streaming_status: Generated<string | null>;
  type: string;
  type_version: Generated<string>;
  updated_at: Generated<Timestamp | null>;
}

export interface AuthProviders {
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  provider_data: string | null;
  provider_type: string;
  provider_user_id: string | null;
  user_id: string;
}

export interface BrainstormFlows {
  artifact_created_at: Timestamp | null;
  artifact_data: string | null;
  artifact_id: string | null;
  artifact_partial_data: Json | null;
  artifact_status: string | null;
  artifact_type: string | null;
  artifact_updated_at: Timestamp | null;
  error_message: string | null;
  progress_percentage: Numeric | null;
  project_id: string | null;
  project_name: string | null;
  streaming_progress: Numeric | null;
  transform_created_at: Timestamp | null;
  transform_id: string | null;
  transform_status: string | null;
  transform_updated_at: Timestamp | null;
}

export interface HumanTransforms {
  action_type: string;
  change_description: string | null;
  derivation_path: Generated<string | null>;
  derived_artifact_id: string | null;
  interface_context: string | null;
  source_artifact_id: string | null;
  transform_id: string;
  transform_name: string | null;
}

export interface LlmPrompts {
  id: string;
  prompt_role: Generated<string | null>;
  prompt_text: string;
  transform_id: string;
}

export interface LlmTransforms {
  model_name: string;
  model_parameters: string | null;
  raw_response: string | null;
  token_usage: string | null;
  transform_id: string;
}

export interface Projects {
  created_at: Generated<Timestamp | null>;
  description: string | null;
  id: string;
  name: string;
  project_type: Generated<string | null>;
  status: Generated<string | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface ProjectsUsers {
  id: Generated<number>;
  joined_at: Generated<Timestamp | null>;
  project_id: string;
  role: Generated<string | null>;
  user_id: string;
}

export interface TransformInputs {
  artifact_id: string;
  id: Generated<number>;
  input_role: string | null;
  transform_id: string;
}

export interface TransformOutputs {
  artifact_id: string;
  id: Generated<number>;
  output_role: string | null;
  transform_id: string;
}

export interface Transforms {
  created_at: Generated<Timestamp | null>;
  error_message: string | null;
  execution_context: string | null;
  id: string;
  max_retries: Generated<number | null>;
  progress_percentage: Generated<Numeric | null>;
  project_id: string;
  retry_count: Generated<number | null>;
  status: Generated<string | null>;
  streaming_status: Generated<string | null>;
  type: string;
  type_version: Generated<string>;
  updated_at: Generated<Timestamp | null>;
}

export interface Users {
  created_at: Generated<Timestamp | null>;
  display_name: string | null;
  id: string;
  status: Generated<string | null>;
  updated_at: Generated<Timestamp | null>;
  username: string;
}

export interface UserSessions {
  created_at: Generated<Timestamp | null>;
  expires_at: Timestamp;
  id: string;
  user_id: string;
}

export interface DB {
  artifacts: Artifacts;
  auth_providers: AuthProviders;
  brainstorm_flows: BrainstormFlows;
  human_transforms: HumanTransforms;
  llm_prompts: LlmPrompts;
  llm_transforms: LlmTransforms;
  projects: Projects;
  projects_users: ProjectsUsers;
  transform_inputs: TransformInputs;
  transform_outputs: TransformOutputs;
  transforms: Transforms;
  user_sessions: UserSessions;
  users: Users;
}
